### ISSUE TITLE
Cannot compile samples

### ISSUE THREAD

**Issue by alanrose** [dem-net/Samples#7]
Despite references to DEM.Net,Core and DEM.NET.glTF when I compile samples I cannot find type IglTFService

**Comment by xfischer** [comment]
Hi @alanrose. Things may be broken now. But I'll help you to fix that.
Do you have referenced the Nuget packages or the projects ?

**Comment by xfischer** [comment]
@alanrose Thanks for reporting this. It was a real mess and it's now fixed.
Please pull latest changes. (tag 0.2.0)
- Samples are now referencing Nugets 0.2.0, which matches DEM.Net master branch

If you want to debug Core and glTF libraries along with the samples, you'll have to 
1) manually clone the master repo with the following file structure : 
Directory
|__ DEM.Net repo
|__ DEM.Net sample repo
2) remove nuget references from sample project
3) add dem net Core and glTF projects to the solution
4) in Sample project, add a project reference to both Core and glTF projects

**Comment by alanrose** [comment]
Thank you for the quick response. I will it a go.

**Comment by alanrose** [comment]
All OK now. Thanks
I look forward to reviewing the library. FWIW I see you have a to do item with producing Quantized Meshes for Cesium. Let me know if you need some help, as I have done this already.

FYI a quick run through of the demo and I see there are some Unauthorized exceptions trying to get the following datasets.
https://e4ftl01.cr.usgs.gov//ASTER_B/ASTT/ASTGTM.003/2000.03.01/ASTGTMV003_N47E015.zip
https://e4ftl01.cr.usgs.gov//ASTER_B/ASTT/ASTGTM.003/2000.03.01/ASTGTMV003_N43E005.zip
etc

**Comment by xfischer** [comment]
You need a free Earth Login account : https://urs.earthdata.nasa.gov/users/new

One done, fill the appsettings.json where you should find placeholders for the login and token. 
You can externalize this as secrets.json file in order to leave this sensitive data ignored by source control.

I would appreciate a lot if you can help on Quantized meshes. I want to use this as part of the triangulation first, to produce low poly GlTF models. 
Join the Slack (link on https://elevationapi.com) to talk about this.
